CREATE TABLE IF NOT EXISTS hits (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app_name varchar(64) NOT NULL,
	request_uri varchar NOT NULL,
	requester_ip varchar(16) NOT NULL,
	request_date timestamp without time zone NOT NULL,
	CONSTRAINT hits_pk PRIMARY KEY (id)
);

-- Column comments

COMMENT ON COLUMN public.hits.id IS 'Идентификатор записи';
COMMENT ON COLUMN public.hits.app_name IS 'Идентификатор сервиса для которого записывается информация';
COMMENT ON COLUMN public.hits.request_uri IS 'URI для которого был осуществлен запрос';
COMMENT ON COLUMN public.hits.requester_ip IS 'IP-адрес пользователя, осуществившего запрос';
COMMENT ON COLUMN public.hits.request_date IS 'Дата и время, когда был совершен запрос к эндпоинту';
