version: '3.1'
services:
  stats-server:
    build: stats
    image: tonasd/explore-with-me:stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: server
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
