CREATE TABLE IF NOT EXISTS public.users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(256) NOT NULL,
	name varchar(250) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT uq_email UNIQUE (email)
);

-- Column comments

COMMENT ON COLUMN public.users.id IS 'Идентификатор';
COMMENT ON COLUMN public.users.email IS 'Почтовый адрес';
COMMENT ON COLUMN public.users.name IS 'Имя с фамилией';

CREATE TABLE IF NOT EXISTS public.categories (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(50) NOT NULL,
	CONSTRAINT categories_pk PRIMARY KEY (id),
	CONSTRAINT uq_category_name UNIQUE ("name")
);

-- Column comments

COMMENT ON COLUMN public.categories.id IS 'Идентификатор категории';
COMMENT ON COLUMN public.categories."name" IS 'Наименование категории';

