CREATE TABLE IF NOT EXISTS public.users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(256) NOT NULL,
	name varchar(250) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT uq_email UNIQUE (email)
);

-- Column comments

COMMENT ON COLUMN public.users.id IS 'Идентификатор';
COMMENT ON COLUMN public.users.email IS 'Почтовый адрес';
COMMENT ON COLUMN public.users.name IS 'Имя с фамилией';

